export const PARSE_SERVER_INSTANCE = 'PARSE_SERVER_INSTANCE';
export const PARSE_SERVER_CLOUD_OPTIONS = 'PARSE_SERVER_CLOUD_OPTIONS';

// cloud job & function
export const PARSE_SERVER_CLOUD_JOB_OPTIONS = 'PARSE_SERVER_CLOUD_JOB_OPTIONS';
export const PARSE_SERVER_CLOUD_FUNC_OPTIONS =
  'PARSE_SERVER_CLOUD_FUNC_OPTIONS';

// cloud save triggers
export const PARSE_SERVER_CLOUD_BEFORE_SAVE_OPTIONS =
  'PARSE_SERVER_CLOUD_BEFORE_SAVE_OPTIONS';
export const PARSE_SERVER_CLOUD_AFTER_SAVE_OPTIONS =
  'PARSE_SERVER_CLOUD_AFTER_SAVE_OPTIONS';

// cloud delete triggers
export const PARSE_SERVER_CLOUD_BEFORE_DELETE_OPTIONS =
  'PARSE_SERVER_CLOUD_BEFORE_DELETE_OPTIONS';
export const PARSE_SERVER_CLOUD_AFTER_DELETE_OPTIONS =
  'PARSE_SERVER_CLOUD_AFTER_DELETE_OPTIONS';

// cloud find triggers
export const PARSE_SERVER_CLOUD_BEFORE_FIND_OPTIONS =
  'PARSE_SERVER_CLOUD_BEFORE_FIND_OPTIONS';
export const PARSE_SERVER_CLOUD_AFTER_FIND_OPTIONS =
  'PARSE_SERVER_CLOUD_AFTER_FIND_OPTIONS';

// session triggers
export const PARSE_SERVER_CLOUD_BEFORE_LOGIN_OPTIONS =
  'PARSE_SERVER_CLOUD_BEFORE_LOGIN_OPTIONS';
export const PARSE_SERVER_CLOUD_AFTER_LOGOUT_OPTIONS =
  'PARSE_SERVER_CLOUD_AFTER_LOGOUT_OPTIONS';

export const PARSE_SERVER_OPTION_PROVIDER = 'PARSE_SERVER_OPTION_PROVIDER';
export const PARSE_SERVER_LOGGER_PROVIDER = 'PARSE_SERVER_LOGGER_PROVIDER';
